### model
model_name_or_path: Qwen/Qwen3-VL-8B-Instruct
image_max_pixels: 2250000
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_alpha: 128
lora_target: all
deepspeed: examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: abhuman_anomaly,had_anomaly,cocohuman_normal
# mix_strategy: interleave_under
# interleave_probs: 0.98,0.02  
template: qwen3_vl
cutoff_len: 16000
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 64
dataloader_num_workers: 64

### output
output_dir: /blob/Qwen_abhuman/qwen3vl-8b/v4/batch_64
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb                 # <--- 核心修改：将 none 改为 wandb
run_name: qwen3vl_8b_abhuman_v4  # <--- 新增：这次训练任务的名称（显示在WandB列表里）
# wandb_project: HumanRefiner_SFT  # <--- 新增：WandB 的项目名称（用于归类）
# wandb_watch: false     

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 2.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.05                    # 拿出 5% 的数据作为验证集 (约 2850 条)
per_device_eval_batch_size: 2     # 验证时的 Batch Size，A100 上可以和训练保持一致或稍大
eval_strategy: steps               # 按步数评估
eval_steps: 500            # 每 500 步评估一次